"""Firstboot bundle generation. Per design spec §6.3-6.4."""
from __future__ import annotations

import json
from pathlib import Path

from astromechos_imager.core.models import (
    Ed25519Pair,
    FirstbootConfig,
    Role,
)


def render_init_cfg(cfg: FirstbootConfig) -> bytes:
    """Generate /boot/astromech_init.cfg — INI-style.

    Refs firstboot_setup.sh:80, 304, 325-326, 355-356.
    Keys in [hotspot] are EXACTLY 'ssid' and 'password' (not '_bootstrap').
    [slave] section only emitted when slave hostname diverges from default.
    """
    lines: list[str] = [
        f"# Generated by AstromechOS Imager {cfg.imager_version} on {cfg.flashed_at_iso}",
        "# DO NOT EDIT — consumed and self-destructed on first boot.",
        "",
        "[system]",
        f"user = {cfg.install_user}",
    ]
    if cfg.repo_url:
        lines += [
            "",
            "[github]",
            f"repo_url = {cfg.repo_url}",
            f"branch = {cfg.repo_branch}",
        ]
    if cfg.hotspot_bootstrap is not None:
        # Contract: keys are EXACTLY 'ssid' and 'password' — firstboot_setup.sh:377-378
        # (and the same cfg_get + awk parser in lib_config.sh:66-71).
        # ``key_mgmt = wpa-psk`` is declared explicitly to pin the
        # WPA2 contract: live ``setup_master_network.sh:356,412`` and
        # ``setup_slave_network.sh:228`` hard-code
        # ``wifi-sec.key-mgmt wpa-psk`` already, so this field is
        # documentary (the awk parsers only fetch ``ssid``+``password``)
        # but completes the configuration declaration.
        lines += [
            "",
            "[hotspot]",
            f"ssid = {cfg.hotspot_bootstrap.ssid}",
            f"password = {cfg.hotspot_bootstrap.password}",
            "key_mgmt = wpa-psk",
        ]
    if cfg.hostname_slave != "astromech-slave":
        # firstboot_setup.sh:355 falls back to astromech-slave.local; only emit on diverge
        lines += [
            "",
            "[slave]",
            f"host = {cfg.hostname_slave}.local",
        ]
    return ("\n".join(lines) + "\n").encode("utf-8")


def render_init_config_json(cfg: FirstbootConfig, role: Role) -> bytes:
    """Generate /boot/astromech_secrets/init_config.json.

    Refs firstboot_setup.sh:161-185.
    """
    obj = {
        "role": role.value,
        "hostname": cfg.hostname_master if role is Role.MASTER else cfg.hostname_slave,
        "imager_version": cfg.imager_version,
        "flashed_at": cfg.flashed_at_iso,
    }
    return (json.dumps(obj, indent=2) + "\n").encode("utf-8")


def render_authorized_keys(
    cfg: FirstbootConfig,
    role: Role,
    master_pub: bytes | None,
) -> bytes:
    """Generate /boot/astromech_secrets/authorized_keys.

    Refs firstboot_setup.sh:124-141 (atomic append + awk dedup on the Pi side).
    Slave inherits master's pubkey so master→slave SSH works post-firstboot.
    Trailing \\n required by awk 'NF' on the Pi side.
    """
    keys = [k.strip() for k in cfg.authorized_keys]
    if role is Role.SLAVE and master_pub is not None:
        keys.append(master_pub.decode("ascii").strip())
    # Trailing \n required by awk 'NF' on the Pi side
    return ("\n".join(keys) + "\n").encode("utf-8")


def _shell_escape_single_quoted(s: str) -> str:
    r"""Wrap ``s`` in single quotes for POSIX shell, escaping embedded ``'``.

    POSIX trick: ``'`` cannot be escaped inside single quotes, so we close
    the string, emit a literal ``\'``, and reopen — ``'foo'\''bar'`` is
    parsed by sh as ``foo'bar``. Also rejects embedded newlines and NULs
    so a malicious SSID/PSK cannot smuggle in a second VAR= line.
    """
    if "\n" in s or "\r" in s or "\x00" in s:
        raise ValueError(
            "wlan_conf value contains a newline or NUL — refusing to write"
        )
    return "'" + s.replace("'", "'\\''") + "'"


def render_wlan_conf(ssid: str, psk: str) -> bytes:
    """Generate /boot/astromech_wlan.conf for the wlan1 home Wi-Fi dongle.

    Format: INI with a single ``[home_wifi]`` section, mirroring the
    exact awk parser in the live ``astromech_wlan_setup.sh:81-92``::

        SSID=$(awk -F= -v s="[home_wifi]" -v k="ssid" ...)
        PSK=$(awk  -F= -v s="[home_wifi]" -v k="password" ...)

    so the live script picks up our values verbatim and creates the
    ``astromech-internet`` NetworkManager profile with
    ``wifi-sec.key-mgmt wpa-psk`` (line 136 of the same script —
    WPA2-PSK is enforced by the Pi side, no key_mgmt field is needed
    in this file). Same format is used by ``local.cfg [home_wifi]``
    so the live ``cfg_get home_wifi <key>`` fallback waterfall stays
    coherent across both sources.

    Defence in depth: ``ssid`` / ``psk`` are validated separately at
    ``FirstbootConfig.__post_init__`` via
    ``validate_wifi_ssid`` / ``validate_wifi_psk`` (IEEE 802.11i:
    8-63 ASCII printable for the PSK = WPA2-PSK contract). Here we
    only reject embedded ``\n`` / ``\r`` / ``\x00`` which would let
    a malicious value smuggle in a second INI line.

    Audit Info #51 (carried over from the shell-format version):
    line-injection chars are still rejected ; the value side of each
    ``key = value`` pair stays verbatim because the live awk
    ``gsub(/^[[:space:]]+|[[:space:]]+$/, "", $2)`` only strips
    surrounding whitespace and accepts any character in between.
    UTF-8 encoded to support Unicode SSIDs.
    """
    for v in (ssid, psk):
        if "\n" in v or "\r" in v or "\x00" in v:
            raise ValueError(
                "wlan_conf value contains a newline or NUL — refusing to write"
            )
    return (
        "[home_wifi]\n"
        f"ssid = {ssid}\n"
        f"password = {psk}\n"
        # WPA2 / WPA-PSK declared explicitly. The live awk parser does
        # not read this field (it only fetches ``ssid`` + ``password``)
        # — the Pi enforces wpa-psk at NM-creation time
        # (``astromech_wlan_setup.sh:136`` hard-codes
        # ``wifi-sec.key-mgmt wpa-psk``). Writing it here documents
        # operator intent and pins the contract for future tooling.
        "key_mgmt = wpa-psk\n"
    ).encode("utf-8")


from astromechos_imager.core.errors import (  # noqa: E402
    BundleSelfValidationFailedError,
    PairAsymmetryError,
)
from astromechos_imager.core.network_config_generator import (  # noqa: E402
    generate_network_config_slave,
)
from astromechos_imager.core.validators import (  # noqa: E402
    OPENSSH_PUBKEY_RE,
    validate_hostname,
)


class FirstbootBundle:
    """Orchestrates per-SD bundle writing in the exact order required by safety.

    Trigger marker LAST so any failure leaves the SD in a known
    BOOTABLE_NO_FIRSTBOOT state (Pi boots fine, firstboot stays dormant,
    operator re-flashes safely). Per design spec §6.4.
    """

    def __init__(self, cfg: FirstbootConfig, master_pair: Ed25519Pair) -> None:
        self.cfg = cfg
        self.master_pair = master_pair

    def write_to(self, bp: object, role: Role) -> None:
        """Write the full firstboot bundle to boot partition bp.

        Write order is CONTRACT-CRITICAL — do not reorder:
        1. mkdir /astromech_secrets
        2. write init_config.json
        3. write authorized_keys
        4. (MASTER ONLY) write id_ed25519 + id_ed25519.pub
        5. write /astromech_init.cfg
        6. write /hw_layout.json (if configured)
        7. _self_validate — raises on contract violation, no trigger written
        8. write /ASTROMECH_FIRSTBOOT_READY (MUST BE LAST)
        """
        # 1. Secrets directory (chmod 0700 ignored on FAT32; firstboot re-applies)
        bp.mkdir("/astromech_secrets")  # type: ignore[union-attr]
        # 2. init_config.json
        bp.write_bytes(  # type: ignore[union-attr]
            "/astromech_secrets/init_config.json",
            render_init_config_json(self.cfg, role),
        )
        # 3. authorized_keys (slave gets master pub appended)
        master_pub = self.master_pair.public_openssh
        bp.write_bytes(  # type: ignore[union-attr]
            "/astromech_secrets/authorized_keys",
            render_authorized_keys(self.cfg, role, master_pub),
        )
        # 4. id_ed25519 keypair (MASTER ONLY) — refs firstboot_setup.sh:146-158
        if role is Role.MASTER:
            bp.write_bytes("/astromech_secrets/id_ed25519", self.master_pair.private_openssh)  # type: ignore[union-attr]
            bp.write_bytes("/astromech_secrets/id_ed25519.pub", master_pub)  # type: ignore[union-attr]
        # 5. astromech_init.cfg
        bp.write_bytes("/astromech_init.cfg", render_init_cfg(self.cfg))  # type: ignore[union-attr]
        # 6. hw_layout.json (optional) — refs firstboot_setup.sh:253-262
        hw = self.cfg.hw_layout_master if role is Role.MASTER else self.cfg.hw_layout_slave
        if hw is not None:
            bp.write_bytes("/hw_layout.json", Path(hw).read_bytes())  # type: ignore[union-attr]
        # 6.5 — Optional WiFi creds for wlan1 (MASTER ONLY — slave joins
        #       the master hotspot via /astromech_init.cfg + network-config,
        #       it has no USB dongle and never wires wlan1).
        if role is Role.MASTER and self.cfg.wifi_ssid and self.cfg.wifi_psk:
            bp.write_bytes("/astromech_wlan.conf", render_wlan_conf(self.cfg.wifi_ssid, self.cfg.wifi_psk))  # type: ignore[union-attr]
        # 6.6 — Slave network-config override (Bug B fix). The Golden
        # Image bakes a stale /boot/firmware/network-config pointing wlan0
        # at the build-machine's home WiFi; left in place, the slave would
        # join the operator's home WiFi on first boot and never reach the
        # master at 192.168.4.1. Overwrite with a netplan v2 wlan0 entry
        # pointing at the master rendezvous hotspot. Master-side network
        # config is managed by NetworkManager via setup_master_network.sh
        # on first boot, so we intentionally do NOT write network-config
        # for the master.
        if role is Role.SLAVE and self.cfg.hotspot_bootstrap is not None:
            bp.write_bytes(  # type: ignore[union-attr]
                "/network-config",
                generate_network_config_slave(
                    self.cfg.hotspot_bootstrap.ssid,
                    self.cfg.hotspot_bootstrap.password,
                ),
            )
        # 7. Self-validate before trigger — raises if contract is violated
        self._self_validate(bp, role)
        # 8. Trigger marker LAST — refs firstboot_setup.sh:67-72
        bp.write_bytes("/ASTROMECH_FIRSTBOOT_READY", b"")  # type: ignore[union-attr]

    def _self_validate(self, bp: object, role: Role) -> None:
        """Defensive contract check. Runs BEFORE the trigger marker is written.

        Uses raise BundleSelfValidationFailedError rather than assert so that
        python -O mode does not silently skip checks.
        """
        try:
            obj = json.loads(bp.read_bytes("/astromech_secrets/init_config.json"))  # type: ignore[union-attr]
            if obj["role"] not in ("master", "slave"):
                raise BundleSelfValidationFailedError(f"bad role {obj['role']!r}")
            validate_hostname(obj["hostname"])
            keys_text = bp.read_bytes("/astromech_secrets/authorized_keys").decode("utf-8")  # type: ignore[union-attr]
            keys = [k.strip() for k in keys_text.splitlines() if k.strip()]
            if role is Role.MASTER:
                # Zero-Touch: authorized_keys on the Master may legitimately
                # be empty — the operator authenticates by password at first
                # login. Only the master keypair (used outbound, master→slave)
                # is strictly required.
                if not bp.exists("/astromech_secrets/id_ed25519"):  # type: ignore[union-attr]
                    raise BundleSelfValidationFailedError("master missing id_ed25519")
                if not bp.exists("/astromech_secrets/id_ed25519.pub"):  # type: ignore[union-attr]
                    raise BundleSelfValidationFailedError("master missing id_ed25519.pub")
            if role is Role.SLAVE:
                # Slave must hold the Master's pubkey, otherwise master→slave
                # SSH never works — the whole Zero-Touch invariant.
                if not any(OPENSSH_PUBKEY_RE.match(k) for k in keys):
                    raise BundleSelfValidationFailedError(
                        "slave authorized_keys missing valid OpenSSH key"
                    )
                master_pub_line = self.master_pair.public_openssh.decode().strip()
                if not any(master_pub_line in k for k in keys):
                    raise BundleSelfValidationFailedError(
                        "slave authorized_keys missing master pubkey "
                        "— master→slave SSH will fail"
                    )
            if self.cfg.hotspot_bootstrap is not None:
                init_cfg_text = bp.read_bytes("/astromech_init.cfg").decode("utf-8")  # type: ignore[union-attr]
                if f"ssid = {self.cfg.hotspot_bootstrap.ssid}" not in init_cfg_text:
                    raise BundleSelfValidationFailedError("hotspot ssid not written")
                if f"password = {self.cfg.hotspot_bootstrap.password}" not in init_cfg_text:
                    raise BundleSelfValidationFailedError("hotspot password not written")
            # WiFi conf: MASTER-only and gated on creds being set.
            # Slave never gets /astromech_wlan.conf — wlan1 is master-only.
            if role is Role.MASTER and self.cfg.wifi_ssid and self.cfg.wifi_psk:
                if not bp.exists("/astromech_wlan.conf"):  # type: ignore[union-attr]
                    raise BundleSelfValidationFailedError(
                        "wifi_ssid and wifi_psk set but /astromech_wlan.conf not written"
                    )
            else:
                if bp.exists("/astromech_wlan.conf"):  # type: ignore[union-attr]
                    raise BundleSelfValidationFailedError(
                        "/astromech_wlan.conf present but role is not master or no wifi creds"
                    )
            # Slave network-config override: when hotspot creds are set, the
            # slave must carry a /network-config pointing wlan0 at the
            # master hotspot SSID. Master must never carry this file (NM
            # manages wlan0 as the AP).
            if role is Role.SLAVE and self.cfg.hotspot_bootstrap is not None:
                if not bp.exists("/network-config"):  # type: ignore[union-attr]
                    raise BundleSelfValidationFailedError(
                        "slave /network-config missing — wlan0 would join Golden's stale WiFi"
                    )
                nc_text = bp.read_bytes("/network-config").decode("utf-8")  # type: ignore[union-attr]
                if self.cfg.hotspot_bootstrap.ssid not in nc_text:
                    raise BundleSelfValidationFailedError(
                        "slave /network-config does not reference the master hotspot SSID"
                    )
            if role is Role.MASTER and bp.exists("/network-config"):  # type: ignore[union-attr]
                # We never write network-config for the master, but the Golden
                # may ship one. Don't tear it down here — NM scripts on first
                # boot supersede netplan via setup_master_network.sh. The
                # check stays informational; no raise.
                pass
        except BundleSelfValidationFailedError:
            raise
        except Exception as e:
            raise BundleSelfValidationFailedError(f"self-validate failed: {e}") from e


def _extract_section(init_cfg_bytes: bytes, section: str) -> str | None:
    """Extract a single [section] block as a normalized string (sorted keys).

    Returns None if the section is absent.
    """
    text = init_cfg_bytes.decode("utf-8")
    out: list[str] = []
    in_section = False
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("[") and s.endswith("]"):
            in_section = s == f"[{section}]"
            continue
        if in_section and "=" in s:
            out.append(s)
    if not out:
        return None
    return "\n".join(sorted(out))


def assert_pair_symmetry(master_bp: object, slave_bp: object) -> None:
    """Verify §2.3 invariants — same [hotspot] block on both cards.

    Raises PairAsymmetryError if the [hotspot] sections differ.
    """
    m_cfg = master_bp.read_bytes("/astromech_init.cfg")  # type: ignore[union-attr]
    s_cfg = slave_bp.read_bytes("/astromech_init.cfg")  # type: ignore[union-attr]
    m_hot = _extract_section(m_cfg, "hotspot")
    s_hot = _extract_section(s_cfg, "hotspot")
    if m_hot != s_hot:
        raise PairAsymmetryError(
            f"master/slave [hotspot] block mismatch — master={m_hot!r} slave={s_hot!r}"
        )
