"""Generate the cloud-init NoCloud ``network-config`` YAML that lives on
the FAT boot partition (``/boot/firmware/network-config`` once the Pi has
booted) and overrides whatever wlan0 / wlan1 configuration is baked into
the Golden Image.

Why this exists
---------------

The Golden Image carries a pre-existing ``network-config`` captured at
build time — typically pointing wlan0 at the build-machine's home
WiFi. If we leave that in place on the **slave** card the slave joins
the operator's home WiFi at first boot and never reaches the master at
``192.168.4.1``: the master→slave pair-seal handshake (the SSH key trust
boot-strap that pins ``Astromech-XXXX``) silently fails.

Per-role contract (AstromechOS dual-WLAN architecture, CLAUDE.md
Invariant #2):

* **Slave**: wlan0 = client joining the master's
  ``Astromech-XXXX`` rendezvous hotspot. Credentials come from
  ``hotspot_bootstrap`` (the same fields written into
  ``[hotspot]`` of ``/astromech_init.cfg``).  No wlan1 — the slave
  never gets a USB dongle.
* **Master**: wlan0 = AP. wlan1 = client joining home WiFi (via
  ``astromech_wlan_setup.sh`` on first boot — NetworkManager owns
  wlan1, not netplan). We deliberately do NOT write a master
  ``network-config`` here because netplan + NetworkManager fighting
  over wlan0 at boot is a known source of races (the live
  ``setup_master_network.sh`` brings the AP up via ``nmcli`` and
  declares ``connection.autoconnect yes``).

Format
------

The Pi OS Trixie cloud-init pipeline accepts the v2 netplan-style
``network:`` block. Example slave output::

    network:
      version: 2
      wifis:
        wlan0:
          dhcp4: true
          optional: true
          access-points:
            "Astromech-1234":
              password: "astropass123"

We use the **plaintext password form** (not the pre-shared key hash)
because the SSID is generated fresh per burn (``keygen
.generate_hotspot_ssid``) and the master rotates to a per-CPU-serial
SSID on first boot anyway — so any pre-computed hash would be wrong
within seconds of first boot. Plaintext on the boot FAT is the
shortest-lived and is wiped/replaced by NetworkManager once the
master has rotated the rendezvous.

Defence in depth: ``ssid`` / ``psk`` are validated by
``validate_ssid`` / ``validate_wpa2_psk`` at
``HotspotBootstrap`` construction time. Here we additionally reject
embedded ``\n`` / ``\r`` / ``\x00`` so a smuggled YAML line cannot
escape the access-points map.
"""
from __future__ import annotations


def _yaml_dquote(value: str) -> str:
    """Double-quote a scalar for YAML.

    YAML double-quoted strings support C-style escapes; we escape only the
    characters that would break out of the quoted scalar (``\\`` and
    ``"``). Embedded newlines / NULs are rejected up front because they
    would let a malicious SSID/PSK smuggle in a second YAML line — the
    netplan parser would silently accept the second access-points key and
    we would join the wrong network.
    """
    if "\n" in value or "\r" in value or "\x00" in value:
        raise ValueError(
            "network-config value contains a newline or NUL — refusing to write"
        )
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return '"' + escaped + '"'


def generate_network_config_slave(hotspot_ssid: str, hotspot_psk: str) -> bytes:
    """Build the slave's ``network-config`` so wlan0 joins the master hotspot.

    The slave has no USB dongle (wlan1 absent by hardware design), so we
    only declare wlan0. ``optional: true`` lets the boot continue if the
    master hotspot is briefly unreachable (initramfs would otherwise wait
    indefinitely for wlan0 to come up).

    Parameters
    ----------
    hotspot_ssid:
        Master rendezvous SSID — same value written into
        ``[hotspot] ssid`` of ``/astromech_init.cfg``.
    hotspot_psk:
        Plaintext WPA2-PSK passphrase — same value written into
        ``[hotspot] password`` of ``/astromech_init.cfg``.
    """
    ssid_q = _yaml_dquote(hotspot_ssid)
    psk_q = _yaml_dquote(hotspot_psk)
    lines = [
        "# Generated by AstromechOS Imager — slave wlan0 joins master hotspot.",
        "# DO NOT EDIT — overrides the Golden Image's stale network-config.",
        "network:",
        "  version: 2",
        "  wifis:",
        "    wlan0:",
        "      dhcp4: true",
        "      optional: true",
        "      access-points:",
        f"        {ssid_q}:",
        f"          password: {psk_q}",
        "",
    ]
    return ("\n".join(lines)).encode("utf-8")
