"""Platform-IO Protocols. Lives in core/ so other core modules never import platform/.

Concrete implementations:
  - platform/windows.py provides PlatformIO (WMI + ctypes).
  - core/bootpartition.py provides BootPartition impls (β pyfatfs, α drive letter).
  - tests/conftest.py provides FakeBootPartition (dict-backed).
"""
from __future__ import annotations

from typing import Iterator, Protocol

from astromechos_imager.core.models import DiskRef


class BootPartition(Protocol):
    """FAT32 boot partition access. Path arguments use forward-slash convention,
    relative to the partition root (e.g. '/astromech_secrets/init_config.json')."""

    def write_bytes(self, path: str, data: bytes) -> None: ...
    def read_bytes(self, path: str) -> bytes: ...
    def mkdir(self, path: str) -> None: ...
    def exists(self, path: str) -> bool: ...
    def close(self) -> None: ...


class RawDevice(Protocol):
    """Sector-aligned byte device. Opened by platform/windows.py for raw write/read."""

    sector_size: int
    size_bytes: int

    def write(self, offset: int, data: bytes) -> int: ...
    def read(self, offset: int, length: int) -> bytes: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...


class PlatformIO(Protocol):
    """Top-level platform facade — injected by the CLI/UI entry points."""

    def enumerate_removable_drives(self) -> list[DiskRef]: ...
    def lock_and_dismount(self, letters: tuple[str, ...],
                          physical_drive_id: int | None = None) -> list[int]: ...
    def open_raw_device(self, physical_drive_id: int) -> RawDevice: ...
    def close_handle(self, handle: int) -> None: ...
    def update_disk_properties(self, handle: int) -> None: ...
    def eject_media(self, handle: int) -> None: ...
    def attach_letter_to_unmounted_volume(self, letter: str, physical_drive_id: int, timeout_s: float = 15.0) -> bool: ...
