"""Per design spec §6.5. Regex aligned with firstboot_setup.sh:206 and IEEE 802.11i."""
from __future__ import annotations

import re

from astromechos_imager.core.errors import (
    InvalidAuthorizedKeysError,
    InvalidBranchNameError,
    InvalidHostnameError,  # re-exported for FirstbootConfig collision check
    InvalidHotspotPskError,
    InvalidHotspotSsidError,
    InvalidInstallUserError,
    InvalidRepoUrlError,
    InvalidWifiPskError,
    InvalidWifiSsidError,
)

# Strict RFC 1123, copy of firstboot_setup.sh:206
_HOSTNAME_RE = re.compile(r"^[a-zA-Z0-9](?:-?[a-zA-Z0-9])*$")

OPENSSH_PUBKEY_RE = re.compile(
    # Audit High #17: tightened from the original ``\s+.+`` comment slot
    # (which accepted ``\n``, ``\r``, and NULs and enabled embedded
    # ``authorized_keys`` injection) to a single-line, tab-or-space
    # delimited comment. The wrapping ``[ \t]+\S.*`` rejects any newline
    # in the key OR the comment portion; callers should still pre-strip
    # individual lines and reject inputs containing ``\n`` or ``\x00``.
    r"^(?:ssh-(?:rsa|ed25519|dss)"
    r"|ecdsa-sha2-nistp(?:256|384|521)"
    r"|sk-(?:ssh-ed25519|ecdsa-sha2-nistp256)@openssh\.com)"
    r"[ \t]+[A-Za-z0-9+/=.]+"
    r"(?:[ \t]+\S[^\r\n\x00]*)?$"
)


def _safe_for_authorized_keys(line: str) -> bool:
    """Reject any pubkey line that would write more than one entry."""
    return "\n" not in line and "\r" not in line and "\x00" not in line

_USER_RE = re.compile(r"^[a-z_][a-z0-9_-]{0,31}$")

_REPO_URL_RE = re.compile(
    r"^(?:https://[^\s]+|git@[^\s:]+:[^\s]+)$"
)

# Simplified git refname rules
_BRANCH_RE = re.compile(r"^(?!.*\.\.)(?!/)(?!.*//)[A-Za-z0-9._/-]+$")

# Dual-WLAN bootstrap SSID for wlan0 (private Master↔Slave AP).
# Format: ``Astromech-<4 decimal digits>`` (e.g. ``Astromech-8392``)
# — generated by the Imager per burn so multiple unboxed pairs can
# come up simultaneously in the same workshop without colliding on
# the bootstrap AP. The FINAL per-robot SSID
# ``Astromech_Control_<XXXX>`` is derived Pi-side by
# ``gen_hotspot_ssid.sh`` from the CPU serial at runtime and never
# round-trips through this validator. See
# ``core/keygen.generate_hotspot_bootstrap``.
_SSID_RE = re.compile(r"^Astromech-[0-9]{4}$")


def validate_hostname(h: str) -> None:
    if not h or len(h) > 63 or not _HOSTNAME_RE.match(h):
        raise InvalidHostnameError(h)


def validate_authorized_keys(keys: list[str]) -> None:
    """Validate an authorized_keys list.

    Zero-Touch contract: an empty list is **permitted**. The Master ships
    without an operator pubkey (the operator authenticates with the Pi
    user's password at first login). The Slave still receives the
    Master's public key at write time via
    ``core/customization.py:render_authorized_keys``, and the role-aware
    ``FirstbootBundle._self_validate`` (the same module) enforces that
    the Slave actually carries a valid OpenSSH key before the
    ``ASTROMECHOS_FIRSTBOOT_READY`` trigger marker is written. So an
    empty list here is safe.

    Every non-empty entry must still match ``OPENSSH_PUBKEY_RE``.
    """
    for k in keys:
        # Hard-reject embedded newlines BEFORE strip — strip() would
        # mask the injection by removing the trailer.
        if not _safe_for_authorized_keys(k):
            raise InvalidAuthorizedKeysError(
                "key contains a newline, carriage return, or NUL — "
                "single-line pubkeys only"
            )
        if not OPENSSH_PUBKEY_RE.fullmatch(k.strip()):
            raise InvalidAuthorizedKeysError(f"not an OpenSSH pubkey: {k!r}")


def validate_install_user(u: str) -> None:
    if not _USER_RE.match(u):
        raise InvalidInstallUserError(u)


def validate_repo_url(u: str) -> None:
    if not _REPO_URL_RE.match(u):
        raise InvalidRepoUrlError(u)


def validate_branch_name(b: str) -> None:
    if not b or b.endswith(".lock") or b.endswith("/") or not _BRANCH_RE.match(b):
        raise InvalidBranchNameError(b)


def validate_ssid(s: str) -> None:
    if not _SSID_RE.match(s) or len(s.encode("utf-8")) > 32:
        raise InvalidHotspotSsidError(s)


def validate_wpa2_psk(p: str) -> None:
    if not (8 <= len(p) <= 63) or not p.isascii() or not p.isprintable():
        # Never echo the actual PSK in the message
        raise InvalidHotspotPskError("<redacted: invalid WPA2 PSK>")


def validate_wifi_ssid(s: str) -> None:
    """Relaxed WiFi SSID validator for home/arbitrary networks.

    IEEE 802.11 allows any 1–32 byte UTF-8 sequence (non-empty after strip).
    Distinct from validate_ssid() which enforces the AstromechOS hotspot pattern.
    """
    stripped = s.strip()
    if not stripped:
        raise InvalidWifiSsidError("WiFi SSID must be non-empty after stripping whitespace")
    if len(s.encode("utf-8")) > 32:
        raise InvalidWifiSsidError(
            f"WiFi SSID must be ≤ 32 UTF-8 bytes (got {len(s.encode('utf-8'))})"
        )


def validate_wifi_psk(p: str) -> None:
    """WPA2-PSK passphrase validator for home WiFi credentials.

    Accepts 8–63 ASCII printable characters, matching WPA2-PSK constraints.
    """
    if not (8 <= len(p) <= 63) or not p.isascii() or not p.isprintable():
        raise InvalidWifiPskError("<redacted: invalid WiFi WPA2 PSK>")
