"""Unit tests for ``core.network_config_generator``.

Covers the slave-side ``network-config`` override that fixes Bug B
(Golden Image's stale wlan0 → operator's home WiFi).
"""
from __future__ import annotations

import pytest

from astromechos_imager.core.network_config_generator import (
    generate_network_config_slave,
)


def test_slave_yaml_shape_is_netplan_v2():
    out = generate_network_config_slave("Astromech-1234", "astropass123")
    text = out.decode("utf-8")
    assert text.startswith("# Generated by AstromechOS Imager")
    assert "network:" in text
    assert "  version: 2" in text
    assert "  wifis:" in text
    assert "    wlan0:" in text
    assert "      dhcp4: true" in text
    assert "      optional: true" in text
    assert "      access-points:" in text


def test_slave_yaml_contains_hotspot_ssid_and_psk_double_quoted():
    out = generate_network_config_slave("Astromech-1234", "astropass123")
    text = out.decode("utf-8")
    # YAML double-quoted scalars are emitted verbatim for ASCII payloads.
    assert '"Astromech-1234"' in text
    assert '"astropass123"' in text


def test_slave_yaml_escapes_embedded_double_quotes():
    """A double-quote in the PSK is escaped (\\") rather than terminating
    the scalar early — netplan would otherwise parse only the prefix."""
    out = generate_network_config_slave("Astromech-1234", 'pass"with"quotes')
    text = out.decode("utf-8")
    assert '\\"' in text
    # SSID line must still be intact above the password line
    assert '"Astromech-1234":' in text


def test_slave_yaml_escapes_backslashes():
    """A literal backslash in the PSK is doubled so YAML decodes one back."""
    out = generate_network_config_slave("Astromech-1234", "a\\b\\c12345")
    text = out.decode("utf-8")
    assert "\\\\" in text


def test_slave_yaml_rejects_newline_injection_in_ssid():
    """Defence-in-depth: a smuggled newline in the SSID would let an
    attacker forge a second access-points key. We refuse to write."""
    with pytest.raises(ValueError):
        generate_network_config_slave("Astromech-1234\nrogue", "astropass123")


def test_slave_yaml_rejects_newline_injection_in_psk():
    with pytest.raises(ValueError):
        generate_network_config_slave("Astromech-1234", "astropass\n123")


def test_slave_yaml_rejects_nul_byte():
    with pytest.raises(ValueError):
        generate_network_config_slave("Astromech-1234", "astro\x00pass")


def test_slave_yaml_is_utf8_encoded():
    out = generate_network_config_slave("Astromech-1234", "astropass123")
    assert isinstance(out, bytes)
    # Should round-trip through utf-8 without errors
    out.decode("utf-8")


def test_slave_yaml_ends_with_newline():
    """cloud-init YAML parsers tolerate trailing whitespace, but a final
    newline keeps diffs clean and matches the rest of our boot files."""
    out = generate_network_config_slave("Astromech-1234", "astropass123")
    assert out.endswith(b"\n")
