# tests/unit/test_render_init_cfg.py
from astromechos_imager.core.customization import render_init_cfg
from astromechos_imager.core.models import FirstbootConfig, HotspotBootstrap


VALID_KEY = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIExxxYYY user@host"


def _cfg(**kw):
    base = dict(
        authorized_keys=[VALID_KEY],
        imager_version="0.1.0",
        flashed_at_iso="2026-05-29T02:15:00Z",
    )
    base.update(kw)
    return FirstbootConfig(**base)


def test_minimal_cfg_contains_only_system():
    out = render_init_cfg(_cfg()).decode("utf-8")
    assert "[system]" in out
    assert "user = pi" in out
    assert "[github]" not in out
    assert "[hotspot]" not in out
    assert "[slave]" not in out
    assert out.startswith("# Generated by AstromechOS Imager 0.1.0 on 2026-05-29T02:15:00Z")
    assert out.endswith("\n")


def test_with_repo_url_adds_github_section():
    out = render_init_cfg(_cfg(
        repo_url="https://github.com/me/fork.git", repo_branch="develop"
    )).decode("utf-8")
    assert "[github]" in out
    assert "repo_url = https://github.com/me/fork.git" in out
    assert "branch = develop" in out


def test_with_hotspot_uses_ssid_and_password_keys():
    """Critical contract: keys are EXACTLY 'ssid' and 'password' (not
    '_bootstrap') and the section declares WPA2 explicitly via
    ``key_mgmt = wpa-psk``. Refs firstboot_setup.sh:377-378 +
    setup_master_network.sh:356,412 (live wpa-psk enforcement)."""
    out = render_init_cfg(_cfg(
        hotspot_bootstrap=HotspotBootstrap(ssid="Astromech-3742", password="a" * 32)
    )).decode("utf-8")
    assert "[hotspot]" in out
    assert "ssid = Astromech-3742" in out
    assert "password = " + "a" * 32 in out
    assert "key_mgmt = wpa-psk" in out
    assert "ssid_bootstrap" not in out
    assert "password_bootstrap" not in out


def test_slave_section_only_when_hostname_custom():
    # Default hostname → no [slave]
    out = render_init_cfg(_cfg()).decode("utf-8")
    assert "[slave]" not in out
    # Custom hostname → emits [slave] host
    out2 = render_init_cfg(_cfg(hostname_slave="r2-body")).decode("utf-8")
    assert "[slave]" in out2
    assert "host = r2-body.local" in out2
