"""wlan0 bootstrap SSID lifecycle — WizardState.hotspotSsid contract.

The bootstrap SSID is the SINGLE source of truth. It is minted EARLY at
wizard-state construction (NOT deferred to the flash job), exposed read-only as
``wizardState.hotspotSsid`` (the Landing / Config / Cycle screens all bind to
it), preserved across ``resetForNextCycle()`` (the second card of a pair), and
regenerated by ``endSession()`` (FLASH ANOTHER) so the next deployment can't
camp the previous robot's rendezvous.

WizardState is a QObject, so we replicate the offscreen-Qt guard used elsewhere.
"""
from __future__ import annotations

import os
import re

import pytest

pytestmark = pytest.mark.skipif(
    os.environ.get("QT_QPA_PLATFORM") != "offscreen",
    reason="set QT_QPA_PLATFORM=offscreen to enable wizard-state ssid tests",
)

_SSID_RE = re.compile(r"^Astromech-\d{4}$")


def _state():
    from astromechos_imager.ui.wizard_state import WizardState
    return WizardState()


def test_hotspot_ssid_minted_early_at_init():
    """Available immediately, before any flash / screen navigation."""
    s = _state()
    assert _SSID_RE.match(s.hotspotSsid), s.hotspotSsid


def test_hotspot_ssid_stable_reads():
    """Reading the property never recomputes — both cards rely on a stable id."""
    s = _state()
    assert s.hotspotSsid == s.hotspotSsid


def test_hotspot_ssid_preserved_across_reset_for_next_cycle():
    """The second card of a pair must inherit the SAME SSID."""
    s = _state()
    first = s.hotspotSsid
    s.resetForNextCycle()
    assert s.hotspotSsid == first


def test_hotspot_ssid_regenerated_on_end_session(monkeypatch):
    """FLASH ANOTHER mints a fresh, independent SSID (deterministic via a
    stubbed generator so the test never flakes on a 1/65536 collision)."""
    seq = iter(["Astromech-0001", "Astromech-0002"])
    monkeypatch.setattr(
        "astromechos_imager.ui.wizard_state.generate_hotspot_ssid",
        lambda: next(seq),
    )
    s = _state()                       # consumes 0001 at init
    assert s.hotspotSsid == "Astromech-0001"
    s.endSession()                     # consumes 0002
    assert s.hotspotSsid == "Astromech-0002"


def test_hotspot_ssid_change_signal_on_end_session():
    s = _state()
    received: list[str] = []
    s.hotspotSsidChanged.connect(lambda v: received.append(v))
    s.endSession()
    assert len(received) == 1
    assert _SSID_RE.match(received[0])
